#!/bin/sh
# Select whichever compositor is live. Internal phoc uses the standard
# wlroots virtual input protocols; external KWin uses KDE fake-input.
set -eu

if [ -S /run/user/1000/wayland-0 ]; then
    export XDG_RUNTIME_DIR=/run/user/1000
    export WAYLAND_DISPLAY=wayland-0
    width=${AURORA_PANEL_WIDTH:-1080}
    height=${AURORA_PANEL_HEIGHT:-2340}
    touch_socket=-
elif [ -S /tmp/aurora-plasma-presenter-1000/wayland-presenter ]; then
    export XDG_RUNTIME_DIR=/tmp/aurora-plasma-presenter-1000
    export WAYLAND_DISPLAY=wayland-presenter
    width=${AURORA_PLASMA_WIDTH:-1920}
    height=${AURORA_PLASMA_HEIGHT:-1080}
    touch_socket=/mnt/aurora-presenter/touch.sock
else
    echo "aurora-input-proxy-session: no Aurora compositor socket" >&2
    exit 1
fi

exec /usr/local/bin/aurora-input-proxy \
    /mnt/aurora-control/external-input.fifo "$width" "$height" "$touch_socket"
