#!/bin/sh
set -eu

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export LD_LIBRARY_PATH=/usr/local/lib:/opt/minigbm/lib
export HYBRIS_LD_LIBRARY_PATH=/usr/lib/android:/vendor/lib64:/system/lib64:/odm/lib64:/apex/com.android.runtime/lib64/bionic
export ANDROID_ROOT=/system
export EGL_PLATFORM=null
export HYBRIS_EGLPLATFORM=null

WIDTH=${DET_PLASMA_WIDTH:-1920}
HEIGHT=${DET_PLASMA_HEIGHT:-1080}
POOL_SIZE=${DET_GRALLOC_POOL_SIZE:-3}
GBM_NODE=${DET_GRALLOC_GBM_DEVICE:-auto}

exec /usr/local/bin/det-gralloc-pool \
    /run/determination/gralloc-pool.sock \
    /mnt/determination-presenter/presenter.sock \
    "$WIDTH" "$HEIGHT" "$POOL_SIZE" "$GBM_NODE" 1000
