#!/bin/sh
# Select whichever compositor is live. Internal phoc uses the standard
# wlroots virtual input protocols; external KWin uses KDE fake-input.
set -eu

if [ -S /run/user/1000/wayland-0 ]; then
    export XDG_RUNTIME_DIR=/run/user/1000
    export WAYLAND_DISPLAY=wayland-0
    width=${DET_PANEL_WIDTH:-1080}
    height=${DET_PANEL_HEIGHT:-2340}
    touch_socket=-
elif [ -S /tmp/det-plasma-presenter-1000/wayland-presenter ]; then
    export XDG_RUNTIME_DIR=/tmp/det-plasma-presenter-1000
    export WAYLAND_DISPLAY=wayland-presenter
    width=${DET_PLASMA_WIDTH:-1920}
    height=${DET_PLASMA_HEIGHT:-1080}
    touch_socket=/mnt/determination-presenter/touch.sock
else
    echo "det-input-proxy-session: no Determination compositor socket" >&2
    exit 1
fi

exec /usr/local/bin/det-input-proxy \
    /mnt/det-control/external-input.fifo "$width" "$height" "$touch_socket"
