#!/usr/bin/env python3
"""Launch Squeekboard with an Opal-scoped Material-style GTK user theme."""
import argparse
import json
import os
import pathlib
import shutil


DEFAULT_DARK = {
    'primary': '#cfbdff',
    'on_primary': '#31205f',
    'primary_container': '#4b3a79',
    'on_primary_container': '#eaddff',
    'background': '#17141f',
    'on_surface': '#f0e9f7',
    'on_surface_variant': '#c5bccf',
    'surface_container': '#302b39',
    'surface_container_high': '#403849',
    'outline_variant': '#5d5667',
}

DEFAULT_LIGHT = {
    'primary': '#7355ad',
    'on_primary': '#ffffff',
    'primary_container': '#eaddff',
    'on_primary_container': '#28104e',
    'background': '#f7f0ff',
    'on_surface': '#211d29',
    'on_surface_variant': '#635c6d',
    'surface_container': '#ebe4f1',
    'surface_container_high': '#dfd6e8',
    'outline_variant': '#cbc2d2',
}


def read_preferences(path):
    try:
        data = json.loads(pathlib.Path(path).read_text())
        return data if isinstance(data, dict) else {}
    except (OSError, ValueError, TypeError):
        return {}


def palette(preferences):
    light = bool(preferences.get('light'))
    fallback = DEFAULT_LIGHT if light else DEFAULT_DARK
    generated = preferences.get('dynamicPalette') if preferences.get('dynamicColors') else None
    generated = generated.get('light' if light else 'dark', {}) if isinstance(generated, dict) else {}
    if not isinstance(generated, dict):
        generated = {}
    return {key: str(generated.get(key, value)) for key, value in fallback.items()}


def css_for(preferences):
    colors = palette(preferences)
    return f'''/* Generated by Opal. This file styles only Squeekboard custom widgets. */
sq_view {{
    background-color: {colors['surface_container']};
    color: {colors['on_surface']};
    font-family: "Google Sans Flex", "Inter", sans-serif;
    font-size: 1.34em;
    box-shadow: inset 0 1px alpha({colors['outline_variant']}, 0.42);
}}

sq_button {{
    color: {colors['on_surface']};
    background: {colors['surface_container_high']};
    border: 0;
    border-radius: 15px;
    margin: 3px;
    box-shadow: none;
}}

sq_view.wide sq_button {{
    border-radius: 17px;
    margin: 4px;
}}

sq_button:active {{
    color: {colors['on_primary_container']};
    background: {colors['primary_container']};
}}

sq_button.subtle-highlight,
sq_button.subtle-highlight-2,
sq_button.emoji-group,
sq_button.character-group {{
    background: mix({colors['surface_container_high']}, {colors['primary_container']}, 0.18);
    border: 0;
}}

sq_button.change-view,
sq_button.change-view-2,
sq_button.change-view-3,
sq_button.altline,
sq_button.special,
sq_button.special-2,
sq_button.special-3,
sq_button.wide {{
    color: {colors['on_surface_variant']};
    background: mix({colors['surface_container']}, {colors['on_surface']}, 0.10);
    border: 0;
}}

sq_button.change-view:active,
sq_button.change-view-2:active,
sq_button.change-view-3:active,
sq_button.altline:active,
sq_button.special:active,
sq_button.special-2:active,
sq_button.special-3:active,
sq_button.wide:active {{
    color: {colors['on_primary_container']};
    background: {colors['primary_container']};
}}

sq_button.latched {{
    color: {colors['on_primary_container']};
    background: {colors['primary_container']};
    font-weight: 700;
}}

sq_button.locked {{
    color: {colors['on_primary']};
    background: {colors['primary']};
    font-weight: 700;
}}

sq_button.placeholder,
sq_button.placeholder-2 {{
    background: alpha({colors['surface_container_high']}, 0.34);
    box-shadow: none;
}}

#Return {{
    color: {colors['on_primary']};
    background: {colors['primary']};
    border-radius: 19px;
    font-weight: 700;
}}

#Return:active {{
    color: {colors['on_primary_container']};
    background: {colors['primary_container']};
}}

sq_view.pin sq_button {{
    border-radius: 18px;
    margin: 3px;
}}
'''


def atomic_write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + '.tmp')
    temporary.write_text(text)
    temporary.replace(path)


def prepare_runtime(preferences_path):
    runtime = pathlib.Path(os.environ.get('XDG_RUNTIME_DIR', f'/tmp/opal-osk-{os.getuid()}'))
    root = runtime / 'opal-osk-config'
    gtk = root / 'gtk-3.0'
    atomic_write(gtk / 'gtk.css', css_for(read_preferences(preferences_path)))
    source_config = pathlib.Path(os.environ.get('XDG_CONFIG_HOME', pathlib.Path.home() / '.config'))
    source_settings = source_config / 'gtk-3.0' / 'settings.ini'
    target_settings = gtk / 'settings.ini'
    if source_settings.is_file() and not target_settings.exists():
        target_settings.symlink_to(source_settings)
    source_dconf = source_config / 'dconf'
    target_dconf = root / 'dconf'
    if source_dconf.exists() and not target_dconf.exists():
        target_dconf.symlink_to(source_dconf, target_is_directory=True)
    return root


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--preferences', required=True)
    parser.add_argument('command', nargs=argparse.REMAINDER)
    arguments = parser.parse_args()
    command = arguments.command
    if command and command[0] == '--':
        command = command[1:]
    if not command:
        command = ['squeekboard']
    executable = shutil.which(command[0])
    if not executable:
        raise SystemExit(f'{command[0]} is not installed')
    environment = os.environ.copy()
    environment['XDG_CONFIG_HOME'] = str(prepare_runtime(arguments.preferences))
    environment['GTK_THEME'] = 'Adwaita'
    os.execvpe(executable, [executable, *command[1:]], environment)


if __name__ == '__main__':
    main()
